version: 3.0.8;{build}
branches:
  only:
  - master
environment:
  matrix:
    - DB: '10.2.18'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
    - DB: '10.2.18'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PARAM: 'Visual Studio 14 2015 Win64'
    - DB: '10.2.18'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017'
    - DB: '10.2.18'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PARAM: 'Visual Studio 14 2015'
    - DB: '10.3.11'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
    - DB: '10.1.37'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
    - DB: '10.0.37'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
    - DB: '5.5.62'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'


configuration: RelWithDebInfo
clone_folder: c:\projects\mariadb-connector-c
before_build:
  - cmd: set MYSQL_TEST_USER=root
  - cmd: set MYSQL_TEST_HOST=127.0.0.1
  - cmd: set MYSQL_TEST_PASSWD=
  - cmd: set MYSQL_TEST_PORT=3306
  - cmd: set MYSQL_TEST_DB=testc
  -  cmd: set FILE=http://mariadb.mirrors.ovh.net/MariaDB/mariadb-%DB%/winx64-packages/mariadb-%DB%-winx64.msi
  - ps: Start-FileDownload $Env:FILE -FileName server.msi
  - cmd: msiexec /i server.msi INSTALLDIR=c:\projects\server SERVICENAME=mariadb ALLOWREMOTEROOTACCESS=true /qn
  - cmd: "\"c:\\projects\\server\\bin\\mysql.exe\" -e \"create database testc\" --user=root"
  - cmd: cmake -G "%CMAKE_PARAM%" -DCMAKE_BUILD_TYPE=RelWithDebInfo
build:
  project: mariadb-connector-c.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: cd c:\projects\mariadb-connector-c\unittest\libmariadb
  - cmd: set MARIADB_PLUGIN_DIR=cd c:\projects\mariadb-connector-c\plugins\lib\RelWithDebInfo
  - cmd: ctest -V
